In [82]:
import numpy as np
data=np.random.randn(2,3)
data

array([[-0.65167095,  1.04949954, -0.41558832],
       [-1.32748498,  1.356766  , -0.7937737 ]])

In [83]:
data*10

array([[ -6.51670952,  10.49499536,  -4.1558832 ],
       [-13.27484979,  13.56766003,  -7.93773698]])

In [84]:
data+data

array([[-1.3033419 ,  2.09899907, -0.83117664],
       [-2.65496996,  2.71353201, -1.5875474 ]])

# Indexing

In [85]:
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
arr[5]

5

In [87]:
arr[5:8]

array([5, 6, 7])

In [88]:
arr[5:8]-12

array([-7, -6, -5])

In [89]:
arr_slice=arr[3:6]
arr_slice

array([3, 4, 5])

In [90]:
arr_slice[2]=1234
arr

array([   0,    1,    2,    3,    4, 1234,    6,    7,    8,    9])

In [91]:
arr[3:5]=14
arr

array([   0,    1,    2,   14,   14, 1234,    6,    7,    8,    9])

# 2-D array slicing

In [92]:
import numpy as np
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
arr2d[:2,1:]  ## :2->rows, 1: ->columns

array([[2, 3],
       [5, 6]])

In [95]:
arr2d[1,:2]

array([4, 5])

In [96]:
arr2d[:2,2]

array([3, 6])

In [97]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [98]:
arr2d[:2,1:]=0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# Boolean indexing

In [99]:
import numpy as np
names=np.array(['abc','def','ghi','abc','ghi','xyz','pqs'])
data=np.random.randn(7,4)
names
#print(data)

array(['abc', 'def', 'ghi', 'abc', 'ghi', 'xyz', 'pqs'], dtype='<U3')

In [100]:
data

array([[ 0.09693395, -0.42021798,  0.16166635,  0.24989085],
       [ 0.65034352, -0.36452752, -1.0787556 ,  0.13255789],
       [ 0.00990276,  0.8178852 , -0.82266347, -1.34765113],
       [-0.03963319,  0.09116556, -1.0746934 , -0.15237624],
       [-0.96401422, -0.16039788, -0.2228727 , -0.60423232],
       [-0.95490504,  0.3729936 ,  0.71133255, -0.30832338],
       [ 0.99449096,  0.9174154 ,  0.25913721,  0.02789137]])

In [101]:
names=='abc'

array([ True, False, False,  True, False, False, False])

In [102]:
data[names=='abc']

array([[ 0.09693395, -0.42021798,  0.16166635,  0.24989085],
       [-0.03963319,  0.09116556, -1.0746934 , -0.15237624]])

In [103]:
data[names=='abc',2:]

array([[ 0.16166635,  0.24989085],
       [-1.0746934 , -0.15237624]])

In [104]:
data[names=='abc',3]

array([ 0.24989085, -0.15237624])

In [105]:
data[~(names=='abc')]   ### True becomes false and vice-versa

array([[ 0.65034352, -0.36452752, -1.0787556 ,  0.13255789],
       [ 0.00990276,  0.8178852 , -0.82266347, -1.34765113],
       [-0.96401422, -0.16039788, -0.2228727 , -0.60423232],
       [-0.95490504,  0.3729936 ,  0.71133255, -0.30832338],
       [ 0.99449096,  0.9174154 ,  0.25913721,  0.02789137]])

In [106]:
mask=(names=='abc')|(names=='ghi') ## if both abc and ghi are present,it shows true in that place 
mask

array([ True, False,  True,  True,  True, False, False])

In [107]:
data[mask]

array([[ 0.09693395, -0.42021798,  0.16166635,  0.24989085],
       [ 0.00990276,  0.8178852 , -0.82266347, -1.34765113],
       [-0.03963319,  0.09116556, -1.0746934 , -0.15237624],
       [-0.96401422, -0.16039788, -0.2228727 , -0.60423232]])

In [108]:
data[data<0]=0   ## negative values are replaced with 0
data

array([[0.09693395, 0.        , 0.16166635, 0.24989085],
       [0.65034352, 0.        , 0.        , 0.13255789],
       [0.00990276, 0.8178852 , 0.        , 0.        ],
       [0.        , 0.09116556, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.3729936 , 0.71133255, 0.        ],
       [0.99449096, 0.9174154 , 0.25913721, 0.02789137]])

In [109]:
data[names!='ghi']=7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.00990276, 0.8178852 , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ]])

In [110]:
arr=np.empty((8,4))
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [111]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [112]:
## using negative indices
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [113]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [114]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [115]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Multidimension

In [116]:
np.dot(arr.T,arr)

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

In [117]:
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [118]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [121]:
arr.transpose((2,0,1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [119]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [120]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [123]:
np.arr.T()

AttributeError: module 'numpy' has no attribute 'arr'